# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_auto_20161226_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
